/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_principale (void);
GtkWidget* create_window_ajouter (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_window_supprimer (void);
GtkWidget* create_window_modifier (void);
GtkWidget* create_window_modifier1 (void);
GtkWidget* create_window_afficher (void);
