/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowgererclient (void)
{
  GtkWidget *windowgererclient;
  GtkWidget *fixed1;
  GtkWidget *buttonajouterclient;
  GtkWidget *buttonsupprimerclient;
  GtkWidget *buttonmodifierclient;

  windowgererclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowgererclient), _("Gerer Client"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowgererclient), fixed1);

  buttonajouterclient = gtk_button_new_with_mnemonic (_("Ajouter Client"));
  gtk_widget_show (buttonajouterclient);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonajouterclient, 104, 40);
  gtk_widget_set_size_request (buttonajouterclient, 168, 29);

  buttonsupprimerclient = gtk_button_new_with_mnemonic (_("Supprimer Client"));
  gtk_widget_show (buttonsupprimerclient);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonsupprimerclient, 104, 96);
  gtk_widget_set_size_request (buttonsupprimerclient, 168, 29);

  buttonmodifierclient = gtk_button_new_with_mnemonic (_("Modifier Client"));
  gtk_widget_show (buttonmodifierclient);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonmodifierclient, 104, 152);
  gtk_widget_set_size_request (buttonmodifierclient, 168, 29);

  g_signal_connect ((gpointer) buttonajouterclient, "clicked",
                    G_CALLBACK (on_buttonajouterclient_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsupprimerclient, "clicked",
                    G_CALLBACK (on_buttonsupprimerclient_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifierclient, "clicked",
                    G_CALLBACK (on_buttonmodifierclient_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowgererclient, windowgererclient, "windowgererclient");
  GLADE_HOOKUP_OBJECT (windowgererclient, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowgererclient, buttonajouterclient, "buttonajouterclient");
  GLADE_HOOKUP_OBJECT (windowgererclient, buttonsupprimerclient, "buttonsupprimerclient");
  GLADE_HOOKUP_OBJECT (windowgererclient, buttonmodifierclient, "buttonmodifierclient");

  return windowgererclient;
}

GtkWidget*
create_windowajouterclient (void)
{
  GtkWidget *windowajouterclient;
  GtkWidget *fixed2;
  GtkWidget *entrynom;
  GtkWidget *entryprenom;
  GtkWidget *entrymail;
  GtkWidget *entryadresseid;
  GtkWidget *labelnom;
  GtkWidget *labelprenom;
  GtkWidget *labelmail;
  GtkWidget *labeladresseid;
  GtkWidget *buttonajouter;
  GtkWidget *buttonafficher;
  GtkWidget *buttonretourgererclient1;

  windowajouterclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowajouterclient), _("Ajouter Client"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowajouterclient), fixed2);

  entrynom = gtk_entry_new ();
  gtk_widget_show (entrynom);
  gtk_fixed_put (GTK_FIXED (fixed2), entrynom, 136, 0);
  gtk_widget_set_size_request (entrynom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom), 8226);

  entryprenom = gtk_entry_new ();
  gtk_widget_show (entryprenom);
  gtk_fixed_put (GTK_FIXED (fixed2), entryprenom, 136, 40);
  gtk_widget_set_size_request (entryprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenom), 8226);

  entrymail = gtk_entry_new ();
  gtk_widget_show (entrymail);
  gtk_fixed_put (GTK_FIXED (fixed2), entrymail, 136, 80);
  gtk_widget_set_size_request (entrymail, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymail), 8226);

  entryadresseid = gtk_entry_new ();
  gtk_widget_show (entryadresseid);
  gtk_fixed_put (GTK_FIXED (fixed2), entryadresseid, 136, 120);
  gtk_widget_set_size_request (entryadresseid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadresseid), 8226);

  labelnom = gtk_label_new (_("Nom :"));
  gtk_widget_show (labelnom);
  gtk_fixed_put (GTK_FIXED (fixed2), labelnom, 40, 8);
  gtk_widget_set_size_request (labelnom, 41, 17);

  labelprenom = gtk_label_new (_("Prenom :"));
  gtk_widget_show (labelprenom);
  gtk_fixed_put (GTK_FIXED (fixed2), labelprenom, 40, 48);
  gtk_widget_set_size_request (labelprenom, 64, 17);

  labelmail = gtk_label_new (_("Mail :"));
  gtk_widget_show (labelmail);
  gtk_fixed_put (GTK_FIXED (fixed2), labelmail, 40, 88);
  gtk_widget_set_size_request (labelmail, 41, 17);

  labeladresseid = gtk_label_new (_("AdresseID :"));
  gtk_widget_show (labeladresseid);
  gtk_fixed_put (GTK_FIXED (fixed2), labeladresseid, 40, 120);
  gtk_widget_set_size_request (labeladresseid, 80, 17);

  buttonajouter = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (buttonajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonajouter, 80, 168);
  gtk_widget_set_size_request (buttonajouter, 66, 29);

  buttonafficher = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (buttonafficher);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonafficher, 176, 168);
  gtk_widget_set_size_request (buttonafficher, 66, 29);

  buttonretourgererclient1 = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (buttonretourgererclient1);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonretourgererclient1, 0, 160);
  gtk_widget_set_size_request (buttonretourgererclient1, 64, 37);

  g_signal_connect ((gpointer) buttonajouter, "clicked",
                    G_CALLBACK (on_buttonajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonafficher, "clicked",
                    G_CALLBACK (on_buttonafficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourgererclient1, "clicked",
                    G_CALLBACK (on_buttonretourgererclient1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowajouterclient, windowajouterclient, "windowajouterclient");
  GLADE_HOOKUP_OBJECT (windowajouterclient, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowajouterclient, entrynom, "entrynom");
  GLADE_HOOKUP_OBJECT (windowajouterclient, entryprenom, "entryprenom");
  GLADE_HOOKUP_OBJECT (windowajouterclient, entrymail, "entrymail");
  GLADE_HOOKUP_OBJECT (windowajouterclient, entryadresseid, "entryadresseid");
  GLADE_HOOKUP_OBJECT (windowajouterclient, labelnom, "labelnom");
  GLADE_HOOKUP_OBJECT (windowajouterclient, labelprenom, "labelprenom");
  GLADE_HOOKUP_OBJECT (windowajouterclient, labelmail, "labelmail");
  GLADE_HOOKUP_OBJECT (windowajouterclient, labeladresseid, "labeladresseid");
  GLADE_HOOKUP_OBJECT (windowajouterclient, buttonajouter, "buttonajouter");
  GLADE_HOOKUP_OBJECT (windowajouterclient, buttonafficher, "buttonafficher");
  GLADE_HOOKUP_OBJECT (windowajouterclient, buttonretourgererclient1, "buttonretourgererclient1");

  return windowajouterclient;
}

GtkWidget*
create_windowafficherclient (void)
{
  GtkWidget *windowafficherclient;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkWidget *labellistedespersonne;
  GtkWidget *buttonretourajouterclient;

  windowafficherclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowafficherclient), _("Afficher Client"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowafficherclient), fixed3);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 80, 56);
  gtk_widget_set_size_request (treeview1, 300, 200);

  labellistedespersonne = gtk_label_new (_("liste des personnes"));
  gtk_widget_show (labellistedespersonne);
  gtk_fixed_put (GTK_FIXED (fixed3), labellistedespersonne, 88, 8);
  gtk_widget_set_size_request (labellistedespersonne, 192, 25);

  buttonretourajouterclient = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (buttonretourajouterclient);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonretourajouterclient, 0, 216);
  gtk_widget_set_size_request (buttonretourajouterclient, 64, 37);

  g_signal_connect ((gpointer) buttonretourajouterclient, "clicked",
                    G_CALLBACK (on_buttonretourajouterclient_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowafficherclient, windowafficherclient, "windowafficherclient");
  GLADE_HOOKUP_OBJECT (windowafficherclient, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowafficherclient, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (windowafficherclient, labellistedespersonne, "labellistedespersonne");
  GLADE_HOOKUP_OBJECT (windowafficherclient, buttonretourajouterclient, "buttonretourajouterclient");

  return windowafficherclient;
}

GtkWidget*
create_windowsupprimerclient (void)
{
  GtkWidget *windowsupprimerclient;
  GtkWidget *fixed4;
  GtkWidget *labelsupprimer;
  GtkWidget *entrysupprimer;
  GtkWidget *buttonsupprimer;
  GtkWidget *buttonretourgererclient2;

  windowsupprimerclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowsupprimerclient), _("Supprimer Client"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (windowsupprimerclient), fixed4);

  labelsupprimer = gtk_label_new (_("Adresse ID"));
  gtk_widget_show (labelsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), labelsupprimer, 16, 96);
  gtk_widget_set_size_request (labelsupprimer, 120, 25);

  entrysupprimer = gtk_entry_new ();
  gtk_widget_show (entrysupprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), entrysupprimer, 136, 96);
  gtk_widget_set_size_request (entrysupprimer, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrysupprimer), 8226);

  buttonsupprimer = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (buttonsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonsupprimer, 136, 240);
  gtk_widget_set_size_request (buttonsupprimer, 112, 29);

  buttonretourgererclient2 = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (buttonretourgererclient2);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonretourgererclient2, 0, 232);
  gtk_widget_set_size_request (buttonretourgererclient2, 64, 37);

  g_signal_connect ((gpointer) buttonsupprimer, "clicked",
                    G_CALLBACK (on_buttonsupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourgererclient2, "clicked",
                    G_CALLBACK (on_buttonretourgererclient2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowsupprimerclient, windowsupprimerclient, "windowsupprimerclient");
  GLADE_HOOKUP_OBJECT (windowsupprimerclient, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowsupprimerclient, labelsupprimer, "labelsupprimer");
  GLADE_HOOKUP_OBJECT (windowsupprimerclient, entrysupprimer, "entrysupprimer");
  GLADE_HOOKUP_OBJECT (windowsupprimerclient, buttonsupprimer, "buttonsupprimer");
  GLADE_HOOKUP_OBJECT (windowsupprimerclient, buttonretourgererclient2, "buttonretourgererclient2");

  return windowsupprimerclient;
}

GtkWidget*
create_windowselectionclient (void)
{
  GtkWidget *windowselectionclient;
  GtkWidget *fixed5;
  GtkWidget *labeladresseid;
  GtkWidget *entrymodifier;
  GtkWidget *buttonslection;
  GtkWidget *buttonretourgererclient3;

  windowselectionclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowselectionclient), _("Selection Client"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (windowselectionclient), fixed5);

  labeladresseid = gtk_label_new (_("Adresse ID"));
  gtk_widget_show (labeladresseid);
  gtk_fixed_put (GTK_FIXED (fixed5), labeladresseid, 40, 112);
  gtk_widget_set_size_request (labeladresseid, 88, 25);

  entrymodifier = gtk_entry_new ();
  gtk_widget_show (entrymodifier);
  gtk_fixed_put (GTK_FIXED (fixed5), entrymodifier, 144, 112);
  gtk_widget_set_size_request (entrymodifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymodifier), 8226);

  buttonslection = gtk_button_new_with_mnemonic (_("Selection"));
  gtk_widget_show (buttonslection);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonslection, 144, 232);
  gtk_widget_set_size_request (buttonslection, 88, 29);

  buttonretourgererclient3 = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (buttonretourgererclient3);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonretourgererclient3, 0, 224);
  gtk_widget_set_size_request (buttonretourgererclient3, 64, 37);

  g_signal_connect ((gpointer) buttonslection, "clicked",
                    G_CALLBACK (on_buttonslection_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourgererclient3, "clicked",
                    G_CALLBACK (on_buttonretourgererclient3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowselectionclient, windowselectionclient, "windowselectionclient");
  GLADE_HOOKUP_OBJECT (windowselectionclient, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (windowselectionclient, labeladresseid, "labeladresseid");
  GLADE_HOOKUP_OBJECT (windowselectionclient, entrymodifier, "entrymodifier");
  GLADE_HOOKUP_OBJECT (windowselectionclient, buttonslection, "buttonslection");
  GLADE_HOOKUP_OBJECT (windowselectionclient, buttonretourgererclient3, "buttonretourgererclient3");

  return windowselectionclient;
}

GtkWidget*
create_windowmodifierclient (void)
{
  GtkWidget *windowmodifierclient;
  GtkWidget *fixed6;
  GtkWidget *labelnom;
  GtkWidget *labelprenom;
  GtkWidget *entrynommodifier;
  GtkWidget *entryprenommodifier;
  GtkWidget *entrymailmodifier;
  GtkWidget *buttonmodifier;
  GtkWidget *entryadresseidmodifier;
  GtkWidget *labelmail;
  GtkWidget *labeladresseid;
  GtkWidget *buttonretourselectionclient;

  windowmodifierclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowmodifierclient), _("Modifier Client"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (windowmodifierclient), fixed6);

  labelnom = gtk_label_new (_("Nom :"));
  gtk_widget_show (labelnom);
  gtk_fixed_put (GTK_FIXED (fixed6), labelnom, 40, 48);
  gtk_widget_set_size_request (labelnom, 56, 17);

  labelprenom = gtk_label_new (_("Prenom :"));
  gtk_widget_show (labelprenom);
  gtk_fixed_put (GTK_FIXED (fixed6), labelprenom, 48, 104);
  gtk_widget_set_size_request (labelprenom, 64, 17);

  entrynommodifier = gtk_entry_new ();
  gtk_widget_show (entrynommodifier);
  gtk_fixed_put (GTK_FIXED (fixed6), entrynommodifier, 120, 48);
  gtk_widget_set_size_request (entrynommodifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynommodifier), 8226);

  entryprenommodifier = gtk_entry_new ();
  gtk_widget_show (entryprenommodifier);
  gtk_fixed_put (GTK_FIXED (fixed6), entryprenommodifier, 120, 104);
  gtk_widget_set_size_request (entryprenommodifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenommodifier), 8226);

  entrymailmodifier = gtk_entry_new ();
  gtk_widget_show (entrymailmodifier);
  gtk_fixed_put (GTK_FIXED (fixed6), entrymailmodifier, 120, 152);
  gtk_widget_set_size_request (entrymailmodifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymailmodifier), 8226);

  buttonmodifier = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (buttonmodifier);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonmodifier, 136, 248);
  gtk_widget_set_size_request (buttonmodifier, 72, 29);

  entryadresseidmodifier = gtk_entry_new ();
  gtk_widget_show (entryadresseidmodifier);
  gtk_fixed_put (GTK_FIXED (fixed6), entryadresseidmodifier, 120, 200);
  gtk_widget_set_size_request (entryadresseidmodifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadresseidmodifier), 8226);

  labelmail = gtk_label_new (_("Mail :"));
  gtk_widget_show (labelmail);
  gtk_fixed_put (GTK_FIXED (fixed6), labelmail, 48, 160);
  gtk_widget_set_size_request (labelmail, 48, 17);

  labeladresseid = gtk_label_new (_("Adresse ID :"));
  gtk_widget_show (labeladresseid);
  gtk_fixed_put (GTK_FIXED (fixed6), labeladresseid, 24, 200);
  gtk_widget_set_size_request (labeladresseid, 88, 25);

  buttonretourselectionclient = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (buttonretourselectionclient);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonretourselectionclient, 0, 240);
  gtk_widget_set_size_request (buttonretourselectionclient, 64, 37);

  g_signal_connect ((gpointer) buttonmodifier, "clicked",
                    G_CALLBACK (on_buttonmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourselectionclient, "clicked",
                    G_CALLBACK (on_buttonretourselectionclient_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowmodifierclient, windowmodifierclient, "windowmodifierclient");
  GLADE_HOOKUP_OBJECT (windowmodifierclient, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (windowmodifierclient, labelnom, "labelnom");
  GLADE_HOOKUP_OBJECT (windowmodifierclient, labelprenom, "labelprenom");
  GLADE_HOOKUP_OBJECT (windowmodifierclient, entrynommodifier, "entrynommodifier");
  GLADE_HOOKUP_OBJECT (windowmodifierclient, entryprenommodifier, "entryprenommodifier");
  GLADE_HOOKUP_OBJECT (windowmodifierclient, entrymailmodifier, "entrymailmodifier");
  GLADE_HOOKUP_OBJECT (windowmodifierclient, buttonmodifier, "buttonmodifier");
  GLADE_HOOKUP_OBJECT (windowmodifierclient, entryadresseidmodifier, "entryadresseidmodifier");
  GLADE_HOOKUP_OBJECT (windowmodifierclient, labelmail, "labelmail");
  GLADE_HOOKUP_OBJECT (windowmodifierclient, labeladresseid, "labeladresseid");
  GLADE_HOOKUP_OBJECT (windowmodifierclient, buttonretourselectionclient, "buttonretourselectionclient");

  return windowmodifierclient;
}

