/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowgererclient (void);
GtkWidget* create_windowajouterclient (void);
GtkWidget* create_windowafficherclient (void);
GtkWidget* create_windowsupprimerclient (void);
GtkWidget* create_windowselectionclient (void);
GtkWidget* create_windowmodifierclient (void);
